// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cccscjcqkdzutjkbkpra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjY3NjamNxa2R6dXRqa2JrcHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTAyNDcsImV4cCI6MjA1NTU2NjI0N30.WhYKXsRMkijqh9cUCqreFlC-KtkhdK13O5aBmm9Yz2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);